### ISSUE TITLE
Split off core API and functionality into a SciMLSensitivityCore package

### ISSUE THREAD

**Issue by pepijndevos** [SciML/SciMLSensitivity.jl#1036]
**Is your feature request related to a problem? Please describe.**

SciMLSensitivity.jl depens on various AD packages such as Zygote and Enzyme that pull in a lot of stuff and frequently break on Julia nightly versions.

We depend on SciMLSensitivity.jl to create a sensitivity problem, but use Diffractor for our AD needs.
We frequently run into long precompile times and trouble upgrading our Julia nightly version due to a large number of dependencies that we don't actually use.

**Describe the solution you’d like**

A SciMLSensitivityCore package that allows us to make a sensitivity problem without depending on AD systems we don't use.

**Describe alternatives you’ve considered**

A package extension would be another alternative to gate the AD functionality behind the availability of their respective package, but my understanding is that this would require a breaking API change.

**Additional context**

Happy to help but not super familiar with the code base and don't have the required privileges to make and publish such a package.

**Comment by ChrisRackauckas** [comment]
This doesn't make sense. The pieces that you are talking about removing are part of the core.
