### ISSUE TITLE
train a neural network for Parameter Estimation of Ordinary Differential Equations

### ISSUE THREAD

**Issue by yqlai1993** [SciML/SciMLSensitivity.jl#1049]
is it possible to train a neural network for for Parameter Estimation of Ordinary Differential Equations? The neural network is not used in the example, but it seems to be used in the last image. Would you provide the full code？

**Comment by ChrisRackauckas** [comment]
I'm not sure what example you're referring to?

**Comment by yqlai1993** [comment]
the first example in tutorials

**Comment by ChrisRackauckas** [comment]
There are no neural networks in that example. Is there another tutorial you're thinking of?

**Comment by yqlai1993** [comment]
> There are no neural networks in that example. Is there another tutorial you're thinking of?

Flux.jl is used in the last image. how does it work?

**Comment by ChrisRackauckas** [comment]
That's an old picture, we should update it .

**Comment by yqlai1993** [comment]
> That's an old picture, we should update it .

thx
