### ISSUE TITLE
precompile fails with v7.60.0

### ISSUE THREAD

**Issue by sjdaines** [SciML/SciMLSensitivity.jl#1058]
**Describe the example**

Apologies in advance if this is just temporary version skew whilst updating the ecosystem,
but precompile fails when I updated to SciMLSensitivity v7.60.0

**Minimal Reproducible Example 👇**

This failed for me locally, but the same failure is visible in CI for release v7.60.0, eg 

https://github.com/SciML/SciMLSensitivity.jl/actions/runs/9174143254/job/25224354207

**Error & Stacktrace ⚠️**

From CI failure:

```
 ? SciMLSensitivity
  320 dependencies successfully precompiled in 440 seconds. 8 already precompiled.
  1 dependency failed but may be precompilable after restarting julia
  1 dependency had output during precompilation:
┌ SciMLSensitivity
│  WARNING: Method definition adjoint(ZygoteRules.AContext, typeof(ZygoteRules.literal_getproperty), SciMLBase.AbstractTimeseriesSolution{T, N, A} where A where N where T, Base.Val{:u}) in module SciMLBaseZygoteExt overwritten in module SciMLSensitivity.
│  ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
└  
```

**Additional context**

**Comment by ChrisRackauckas** [comment]
@DhairyaLGandhi you forgot the isdefined

**Comment by DhairyaLGandhi** [comment]
Apologies, I am taking a look.
