### ISSUE TITLE
Consistency in sensealg arguments

### ISSUE THREAD

**Issue by mschytt** [SciML/SciMLSensitivity.jl#1088]
Hi👋

After a small back-and-forth with Chris on slack, we found that the direct sensitivity analysis interfaces for ODEs are not consistent between the forward and adjoint methods. Specifically, I am considering the choice of sensitivity algorithm.

The documentation for ODEForwardSensitivityProblem gives the following signature with `alg` as a positional argument:
```
help?> ODEForwardSensitivityProblem

search: ODEForwardSensitivityProblem ODEForwardSensitivityFunction

  function ODEForwardSensitivityProblem(f::Union{Function,DiffEqBase.AbstractODEFunction}, u0,tspan,p=nothing, alg::AbstractForwardSensitivityAlgorithm = ForwardSensitivity(); kwargs...)
```
but in the explanation of the syntax, it accidently mentions a positional argument `sensealg`:
```
ODEForwardSensitivityProblem(f::SciMLBase.AbstractODEFunction,u0,
                             tspan,p=nothing,
                             sensealg::AbstractForwardSensitivityAlgorithm = ForwardSensitivity();
                             kwargs...)
```
Since `sensealg` is a keyword argument for the common solve interface and the direct adjoint sensitivity interface, users (i.e. me) may accidently and unfruitfully try to specify sensealg as a keyword argument in a call to ODEForwardSensitivityProblem.

Perhaps the positional argument `alg`, should be changed to a keyword argument `sensealg` in line with the remaining interfaces?

Best regards,
Marcus

**Comment by ChrisRackauckas** [comment]
Thanks for the report, it's not fixed with depwarns.
