### ISSUE TITLE
Depending on `OrdinaryDiffEq`?

### ISSUE THREAD

**Issue by prbzrg** [SciML/SciMLSensitivity.jl#1095]
I tried to replace `OrdinaryDiffEq` by `OrdinaryDiffEqDefault` in my code, but because of deps, it's still there:
```julia
 pkg> why OrdinaryDiffEq
  SciMLSensitivity → OrdinaryDiffEq
  SciMLSensitivity → StochasticDiffEq → OrdinaryDiffEq
```

**Comment by ChrisRackauckas** [comment]
You can try removing it and StochasticDiffEq and see if tests still pass.
