### ISSUE TITLE
Forward Mode for Neural ODEs / Structured Parameters broken

### ISSUE THREAD

**Issue by avik-pal** [SciML/SciMLSensitivity.jl#1099]
Test from Optimization.jl: https://github.com/SciML/Optimization.jl/blob/master/test/minibatch.jl
Error: https://github.com/SciML/Optimization.jl/actions/runs/10550106197/job/29225903838#step:7:1169

The ComponentArrays parameters are being converted to regular arrays, so Lux doesn't know how to handle them. ReverseMode works fine.

cc @Vaibhavdixit02 (who also got this failure)

**Comment by Vaibhavdixit02** [comment]
We had some discussion at https://github.com/SciML/ModelingToolkit.jl/issues/2968 Chris's latest comment suggests there might be release coming to fix it

**Comment by ChrisRackauckas** [comment]
Should be fixed in https://github.com/SciML/SciMLSensitivity.jl/pull/1104 and some other related PRs. All tests are at least passing now.
