### ISSUE TITLE
Neural SDE example fails on convert(::Type{Float64}, x::Tracker.TrackedReal{Float64})

### ISSUE THREAD

**Issue by John-Boik** [SciML/SciMLSensitivity.jl#1109]
Note: I have deleted my original post and replaced it with the note here. My post concerned the tutorial [Neural Stochastic Differential Equations](https://docs.juliahub.com/DiffEqSensitivity/02xYn/6.79.0/sde_fitting/neural_sde/#Neural-Stochastic-Differential-Equations). But I realize now that it is outdated, and the new tutorial to follow is [Neural Stochastic Differential Equations With Method of Moments](https://docs.sciml.ai/DiffEqFlux/stable/examples/neural_sde/). 

When I tried to run the new tutorial, I received the same error as before, the first few lines of which are:
```
ERROR: LoadError: MethodError: no method matching Float64(::Tracker.TrackedReal{Float64})

Closest candidates are:
  (::Type{T})(::Real, ::RoundingMode) where T<:AbstractFloat
   @ Base rounding.jl:207
  (::Type{T})(::T) where T<:Number
   @ Core boot.jl:792
  Float64(::IrrationalConstants.Log4π)
   @ IrrationalConstants ~/.julia/packages/IrrationalConstants/vp5v4/src/macro.jl:112
  ...

Stacktrace:
  [1] convert(::Type{Float64}, x::Tracker.TrackedReal{Float64})
    @ Base ./number.jl:7
  [2] setindex!(A::Vector{Float64}, x::Tracker.TrackedReal{Float64}, i1::Int64)
    @ Base ./array.jl:1021
  [3] copyto_unaliased!
    @ ./abstractarray.jl:1094 [inlined]
  [4] copyto!(dest::Vector{Float64}, src::Tracker.TrackedVector{Float64, Vector{Float64}})
    @ Base ./abstractarray.jl:1068
  [5] copyto!
    @ ~/.julia/packages/ComponentArrays/xO4hy/src/similar_convert_copy.jl:42 [inlined]
  [6] copyto!
    @ ./broadcast.jl:997 [inlined]
  [7] copyto!
    @ ./broadcast.jl:956 [inlined]
  [8] materialize!
    @ ./broadcast.jl:914 [inlined]
  [9] materialize!
    @ ./broadcast.jl:911 [inlined]
 [10] restructure(x::ComponentArrays.ComponentVector{…}, y::ComponentArrays.ComponentVector{…})
    @ ArrayInterface ~/.julia/packages/ArrayInterface/TFWPW/src/ArrayInterface.jl:637
```
However, the error was apparently caused by importing some package that was not used in the new tutorial, even though every package I imported was recently updated. In my original example, I imported the following:
```
import Base
import ComponentArrays
import DiffEqBase
import DiffEqFlux
import Lux
import Optimization
import OptimizationFlux
import Plots
import Random
import Statistics
import StochasticDiffEq 
import Zygote
using SciMLSensitivity
```
I'm not sure which imported package caused the problem, but when I generated a new project and imported only the packages used in the new tutorial, the error disappeared. If someone else receives the same error as above, it is likely due to importing packages that are not used or needed in the most recent approach to solving Neural SDEs.

**Comment by John-Boik** [comment]
I mentioned in my main post that the [neural SDE tutorial](https://docs.juliahub.com/DiffEqSensitivity/02xYn/6.79.0/sde_fitting/neural_sde/#Neural-Stochastic-Differential-Equations) example does not run as given. Here are the errors I get when I run the code.

The first is `UndefVarError: ActivationFunction not defined`, which occurs when defining the drift neural network. That can be fixed simply by using `x -> x.^3` instead. 

The next is `ComponentArray not defined` which occurs at  `p1 = Lux.ComponentArray(p1)`. That can be fixed by using `p1 = ComponentArrays.ComponentArray(p1)`.

The next is:
```
MethodError: no method matching (::DiffEqFlux.NeuralDSDE{…})(::Vector{…}, ::Vector{…}, ::@NamedTuple{…}, ::@NamedTuple{})

Closest candidates are:
  (::DiffEqFlux.NeuralDSDE)(::Any, ::Any, ::Any)
   @ DiffEqFlux ~/.julia/packages/DiffEqFlux/TglmB/src/neural_de.jl:95
```
which occurs at `prediction0, st1, st2 = neuralsde(u0,p,st1,st2)`.
This can be fixed by calling Lux.setup on neuralsde, as I mention in my main post:
```
p, st = Lux.setup(rng, neuralsde)
prediction0, st = neuralsde(u0,p,st)
```

**Comment by avik-pal** [comment]
You are looking at an ancient package that has been replaced by SciMLSensitivity. `ActivationFunction` was a thing in Lux 0.3 (I think) which doesn't exist anymore.

Try running https://docs.sciml.ai/DiffEqFlux/stable/examples/neural_sde/

**Comment by ChrisRackauckas** [comment]
Okay yeah, I'd first say that the v6 tutorials are more than 2 years old and won't necessarily be a good guide for v7 usage. There's a major version between them because there are breaking differences, some of which you see and highlighted here. I'd highly recommend just using the updated version and tutorial.
