### ISSUE TITLE
Default algorithm should have checks for Adjoints limitations

### ISSUE THREAD

**Issue by prbzrg** [SciML/SciMLSensitivity.jl#1116]
**Describe the bug 🐞**

I'm getting 
```julia
ERROR: LoadError: autojacvec choice SciMLSensitivity.TrackerVJP(false) is not supported by GaussAdjoint
```
When I don't specify `sensealg`.
I think the default algorithm for selecting `sensealg` doesn't check for limitation of each Adjoint.

**Comment by miguellords** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by ChrisRackauckas** [comment]
What's an MWE for this?

**Comment by ChrisRackauckas** [comment]
There is no default to TrackerVJP, so it cannot be the default algorithm?

**Comment by prbzrg** [comment]
In the function `automatic_sensealg_choice` in the file:
https://github.com/SciML/SciMLSensitivity.jl/blob/master/src/concrete_solve.jl
choosing `vjp` happen before choosing Adjoint and passing `vjp` to it
the selection is separated and independent of each other.

**Comment by prbzrg** [comment]
It's possible that `TrackerVJP` get selected
https://github.com/SciML/SciMLSensitivity.jl/blob/4847a87c3264958efdacf4247c1d69e09d0bf3ef/src/concrete_solve.jl#L167
and then we pass it to `GaussAdjoint`
https://github.com/SciML/SciMLSensitivity.jl/blob/4847a87c3264958efdacf4247c1d69e09d0bf3ef/src/concrete_solve.jl#L198
