### ISSUE TITLE
Release latest `main` to allow Enzyme v0.13

### ISSUE THREAD

**Issue by gdalle** [SciML/SciMLSensitivity.jl#1122]
At the moment, anyone depending on SciMLSensitivity cannot upgrade Enzyme. I see that the relevant CompatHelper PR was merged last week, but the last release of SciMLSensitivity was 2 weeks ago. Would it be possible to tag a new version? 
Ping @ChrisRackauckas 

EDIT: it seems like this should be solved first?

- https://github.com/JuliaDiff/SparseDiffTools.jl/issues/300

**Comment by ChrisRackauckas** [comment]
What's used here shouldn't hit what broke, so at this point I did the release to at least try and remove deadlock, and we'll have to deal with any fallout ASAP.

**Comment by avik-pal** [comment]
We also need a DiffEqBase release
