### ISSUE TITLE
discrete dg/dp

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLSensitivity.jl#286]
If one defines a discrete loss function and utilizes the direct adjoint interface, and that discrete loss function is dependent on the parameters, there is a dg/dp term missing from the adjoint. However, this case does not show up in autodiff (since the cost function is handled separately), which is by far the main use case of discrete adjoints, and it doesn't show up in continuous adjoints because of https://github.com/SciML/DiffEqSensitivity.jl/pull/285 (which is by far the main use case of the direct adjoint interface), so it's really an edge case.

**Comment by ChrisRackauckas** [comment]
I think we should do `dgdu_continuous`, `dgdp_continuous`, `dgdu_discrete` and `dgdp_discrete`, thoughts @frankschae ?

**Comment by frankschae** [comment]
yeah, I think it would be slightly better because it's even more descriptive than the current form with the tuples. Isn't that another breaking change then though?

**Comment by ChrisRackauckas** [comment]
Ehh, no one has adopted SciMLSensitivity.jl by now, it's the first day 😅. I say if we get it in the next week or so it's probably okay to do without a deprecation, especially since it's an obscure feature that (a) will appropriately throw an error (thus no correctness issues to worry about) and (b) wouldn't show up in automatic differentiation or any other high level case. It would only show up if someone was using one specific argument (that's not in any tutorial) in a lower level API the day that the new breaking release came out... okay it might hit someone but I think we're fine 😅 .

**Comment by ChrisRackauckas** [comment]
Closed by https://github.com/SciML/SciMLSensitivity.jl/pull/675
