### ISSUE TITLE
Solution loses one element during differentiation

### ISSUE THREAD

**Issue by baggepinnen** [SciML/SciMLSensitivity.jl#347]
The following loss function prints two numbers from two `@show` statements. While calling `loss(p)`, they are both the same as expected, but when calling `sciml_train`, the solution is one element shorter than the `saveat` vector.  The problem is a simple 4-dimensional ODE wit the `tspan` defined as the extrema of the `saveat` vector.
```
tspan      = extrema(timevec(D.dr))
prob       = ODEProblem{true}(dynamics, x0, tspan, parameters)
```

```julia
function loss(p)
    sol = solve(
        prob,
        Tsit5(),
        p = p,
        saveat = timevec(D.dr),
        sensealg = DiffEqSensitivity.ForwardDiffSensitivity(),
    )
    yh = Array(sol)[2, :]
    @show length(timevec(D.dr))
    @show length(yh)
    cost = sum(abs2.(vec(yh) .- vec(D.dr.y)))
    cost, sol
end

loss(p)
```

**Comment by baggepinnen** [comment]
If I expand the time span like
```
tspan      = extrema(timevec(D.dr)) .+ (-1e-5,1e-5)
```
it works, indicating that there is a difference in rounding or something, causing one of the endpoints in the `saveat` vector not to be included.

**Comment by ChrisRackauckas** [comment]
Do you have an example I can run? This seems very floating point dependent so I'll need an example here.

**Comment by ChrisRackauckas** [comment]
This was fixed by the `t` matching procedure
