### ISSUE TITLE
"Cannot determine ordering of Dual tags" when using stiff solver with ForwardDiffSensitivity

### ISSUE THREAD

**Issue by bgroenks96** [SciML/SciMLSensitivity.jl#393]
```julia
using DiffEqFlux, DiffEqSensitivity, Flux, OrdinaryDiffEq, Zygote, Test #using Plots
using DiffEqBase: get_tmp, dualcache
using ComponentArrays
using Parameters
using ForwardDiff
using ReverseDiff
p = ComponentArray(lvpara=ComponentArray(α=2.2,β=1.0,δ=2.0,γ=0.4),a=1.0,b=1.0)
u0 = ComponentArray(state=ComponentArray(x=1.0,y=1.0))
ax_p = getaxes(p)
ax_u = getaxes(u0)
chunk_size(dual::Type{ForwardDiff.Dual{T,V,N}}) where {T,V,N} = N
select(a::AbstractArray, u::AbstractArray) = a
select(dc::DiffEqBase.DiffCache, u) = get_tmp(dc,u)
struct LotkaVolterra{T}
  d::T
end
function (lv::LotkaVolterra)(du,u_,p,t)
  #@assert chunk_size(eltype(u)) == 2 "found chunk size of $(chunk_size(eltype(u))) for $(typeof(u))"
  #d = get_tmp(d_cache, u)
  u = ComponentArray(u_,ax_u)
  p = ComponentArray(p,ax_p)
  @unpack x,y = u.state
  @unpack lvpara, a, b = p
  @unpack α, β, δ, γ = lvpara
  d = select(lv.d,u)
  d[1] = a^2+b^2
  d[2] = b^2-a^2
  du[1] = dx = (α - β*y)x + d[1]
  du[2] = dy = (δ*x - γ)y + d[2]
end
u0 = Array(u0)
p = Array(p)
lv = LotkaVolterra(dualcache(zeros(2),Val{6}))
prob = ODEProblem(lv,u0,(0.0,1.0),p)
function predict_rd(p)
  Array(solve(prob,Rosenbrock23(chunk_size=6),dt=0.01,p=p,saveat=0.1,reltol=1e-4,sensealg=ForwardDiffSensitivity()))
end
loss_rd(p) = sum(abs2,x-1 for x in predict_rd(p))opt = ADAM(0.1)
cb = function (p,l,pred)
  display(loss_rd(p))
end
@time res = DiffEqFlux.sciml_train(loss_rd, p, opt, maxiters=100)
```

```
Cannot determine ordering of Dual tags ForwardDiff.Tag{SciMLBase.TimeGradientWrapper{ODEFunction{true,LotkaVolterra{DiffEqBase.DiffCache{Array{Float64,1},Array{ForwardDiff.Dual{nothing,Float64,6},1}}},LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,typeof(SciMLBase.DEFAULT_OBSERVED),Nothing},Array{ForwardDiff.Dual{ODEFunction{true,LotkaVolterra{DiffEqBase.DiffCache{Array{Float64,1},Array{ForwardDiff.Dual{nothing,Float64,6},1}}},LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,typeof(SciMLBase.DEFAULT_OBSERVED),Nothing},Float64,6},1},Array{ForwardDiff.Dual{ODEFunction{true,LotkaVolterra{DiffEqBase.DiffCache{Array{Float64,1},Array{ForwardDiff.Dual{nothing,Float64,6},1}}},LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,typeof(SciMLBase.DEFAULT_OBSERVED),Nothing},Float64,6},1}},Float64} and ODEFunction{true,LotkaVolterra{DiffEqBase.DiffCache{Array{Float64,1},Array{ForwardDiff.Dual{nothing,Float64,6},1}}},LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,typeof(SciMLBase.DEFAULT_OBSERVED),Nothing}
≺(::Type{T} where T, ::Type{T} where T) at dual.jl:49
...
```

**Comment by ChrisRackauckas** [comment]
This one is going to be tough. In the meantime, `Rosenbrock23(autodiff=false)` or use MTK to generate with a Jacobian.

**Comment by bgroenks96** [comment]
I see you made a pull request (#396). What's the issue? Does the fix break something else?

In my real application, disabling autodiff does resolve this (of course) but results in a performance hit of 3-4x, so... not ideal.

I don't think MTK is able to parse my ODE function. Last time I checked, `moelingtoolktiize` failed with some obscure error (I think related to the fact that I use in-place vector mutation) and I gave up on it.

**Comment by ChrisRackauckas** [comment]
No, that's not a full fix, it's part of one. But there's still a big portion missing, which is "easy" but extremely tedious and labor intensive to handle. And it will be completely obsoleted by Diffractor.jl, so I'm just going to go bug Keno a bit instead 😆 . But this little detail still makes the tags a little nicer.

>I think related to the fact that I use in-place vector mutation

In-place mutation is fine. It's odd if it would fail on something where autodiff works. Did you open an issue on it? Was it one of the non-standard parameter setup issues?

**Comment by bgroenks96** [comment]
I'll have to check again, I think I tried it last before I got my code working with autodiff. Maybe now MTK will work..?

Anyway, turns out numerical diff doesn't work with sensitivity analysis. Reposting what I put on slack:

> if I specify the Jacobian as a Tridiagonal with type Float64 it will fail when differentiating because everything is of type ForwardDiff.Dual . However, if I define it with type ForwardDiff.Dual it will fail on the forward pass of sensitivity analysis (or with numerical diff) when things are type Float64.

**Comment by ChrisRackauckas** [comment]
That's a separate issue. Can you put the MWE in a separate issue? I'd like to leave this one open to for discussions of `dualcache` handling.

**Comment by bgroenks96** [comment]
@ChrisRackauckas I cannot use `modelingtoolkitize` because it is incompatible with `ComponentArrays`. I get an error `type Array has no field ....` when trying to use it.

**Comment by ChrisRackauckas** [comment]
This was fixed.
