### ISSUE TITLE
QuadratureAdjoint without absolute error

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/SciMLSensitivity.jl#406]
Does adding this option make sense?
`QuadratureAdjoint(abstol = nothing)`

**Comment by ChrisRackauckas** [comment]
What would that do?

**Comment by ArnoStrouwen** [comment]
I probably should have reversed my question: why (and how) does abstol=nothing work for regular solves, but not as an QuadratureAdjoint keyword?
`solve(prob,Tsit5(),abstol=nothing)`

**Comment by ChrisRackauckas** [comment]
That works? Can I get an MWE?

**Comment by ArnoStrouwen** [comment]
```jl
(tester2) pkg> status
      Status `~/tester2/Project.toml`
  [1dea7af3] OrdinaryDiffEq v5.52.3

julia> using OrdinaryDiffEq

julia> f(u,p,t) = 1.01*u
f (generic function with 1 method)

julia> u0 = 1/2
0.5

julia> tspan = (0.0,1.0)
(0.0, 1.0)

julia> prob = ODEProblem(f,u0,tspan)
ODEProblem with uType Float64 and tType Float64. In-place: false
timespan: (0.0, 1.0)
u0: 0.5

julia> sol = solve(prob, Tsit5(),abstol=1e-8)[end]
1.372800440830529

julia> sol = solve(prob, Tsit5(),abstol=nothing)[end]
1.3728004409033037

julia> sol = solve(prob, Tsit5())[end]
1.3728004409033037

julia> sol = solve(prob, Tsit5(),abstol=0.0)[end]
1.372800440829787

julia> sol = solve(prob, Tsit5(),abstol="blah")[end]
ERROR: MethodError: no method matching real(::String)
Closest candidates are:
```

**Comment by ChrisRackauckas** [comment]
@YingboMa did you add special handling of `nothing`? I don't remember doing it.

Well what's the MWE where this then fails?

**Comment by devmotion** [comment]
You did change the default values of `abstol` and `reltol` to `nothing` a while ago: https://github.com/SciML/OrdinaryDiffEq.jl/commit/bf74ddd1e6642d221daf2360d329358233f1df43#diff-ca1c45d4f0bec64e8340981f6b27f4037bf6ac13c8f1af132656c485c0a8e941

**Comment by ChrisRackauckas** [comment]
oh interesting, I see why that works now. That's... unfortunate haha.

**Comment by YingboMa** [comment]
I do like `nothing` default, so we don't have always copy-paste the default value all the time.

**Comment by ChrisRackauckas** [comment]
The defaults were fixed.
