### ISSUE TITLE
Incomplete documentation chunk_size in forward mode

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/SciMLSensitivity.jl#540]
chunk_size: Chunk size for forward mode differentiation if full Jacobians are built (autojacvec=false and autodiff=true). Default is 0 for automatic choice of chunk size.
https://diffeq.sciml.ai/latest/analysis/sensitivity/#Internal-Automatic-Differentiation-Options-(ADKwargs)

This explanation only makes sense for ForwardSensitivity. ForwardDiffSensitivity also has chunk_size, but no full Jacobians are built.

**Comment by ChrisRackauckas** [comment]
Agreed, this needs an update.

**Comment by ChrisRackauckas** [comment]
This was fixed.
