### ISSUE TITLE
Sign of the gradient w.r.t. initial condition

### ISSUE THREAD

**Issue by ilysym** [SciML/SciMLSensitivity.jl#543]
`du0, dp = adjoint_sensitivities(sol, alg, dg, ts)`
it seems that `du0` has wrong sign here: `du0 == -du0_true`.
There is a test for `du0`, but is uses wrong `dg`:
https://github.com/SciML/DiffEqSensitivity.jl/blob/547104399ed173d3a6e077714090bc81235e3044/test/adjoint.jl#L41
`dg(u) = 2.0.-u` while it should be `dg(u) = u.-1.0`.

**Comment by ChrisRackauckas** [comment]
Yeah I think @frankschae and @YingboMa noticed this too. We end up correcting the sign in `concrete_solve`, so people who use AD for the derivatives (99.99% of users) will get the right gradient, but it is still odd. I think we should probably just correct this with a breaking release ASAP.

**Comment by ChrisRackauckas** [comment]
The signs were corrected in the update to SciMLSensitivity.jl
