### ISSUE TITLE
SDE Controls tutorial fix

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SciMLSensitivity.jl#661]
@frankschae can you take this on? I left this out of https://github.com/SciML/DiffEqSensitivity.jl/pull/659, but it's the last tutorial to fix other than https://github.com/SciML/DiffEqSensitivity.jl/pull/635

**Comment by frankschae** [comment]
Should we switch to Lux + Optimization.jl for this example too?

**Comment by ChrisRackauckas** [comment]
If you want. I don't think the choice is so important for Lux vs Flux right now. Optimization.jl, yes we should.

**Comment by ChrisRackauckas** [comment]
I removed the running in #662 to execute the DiffEqSensitivity -> SciMLSensitivity change with correct docs, but once that's done, let's open up the PR again and see why it stalled.

**Comment by frankschae** [comment]
hmm it was finished on my machine over lunch and I checked the plot. I'll check how expensive it actually is.

**Comment by ChrisRackauckas** [comment]
Too high of a peak memory requirement will easily kill the CI computers. That might be it

**Comment by ChrisRackauckas** [comment]
Looks like it's fixed, other metaissue
