### ISSUE TITLE
Zygote fails when using DAE with mass matrix and sensealg = InterpolatingAdjoint(autojacvec=ZygoteVJP())

### ISSUE THREAD

**Issue by raphaelchinchilla** [SciML/SciMLSensitivity.jl#686]
Zygote gets an error when one solves a DAE with mass matrix and chooses `sensealg = InterpolatingAdjoint(autojacvec=ZygoteVJP())`. I have the gut feeling that this bug is somehow related to the one I reported in #685. Here is a MRE.

```
using DifferentialEquations, SciMLSensitivity, Zygote, ForwardDiff, LinearAlgebra
x0=[1.0, 0, 0, 0, 0] 
tspan=(0.0,10.0) 
p = [9.8]
Δt=0.1

## Pendulum in DAE form already simplified to index 1
function f(u,p,t) 
    x, dx, y, dy, T = u
    g, = p
    [dx;
    T*x;
    dy;
    T*y - g;
    2*(dx^2+dy^2+y*(y*T-g)+T*x^2)]
end

f_fun = ODEFunction{false}(f, mass_matrix=Diagonal([1,1,1,1,0]))
prob_DAE = ODEProblem{false}(f_fun, x0, tspan, p)

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(),saveat=Δt,p=p)))
end
#([-239.0565625836705],)

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(),saveat=Δt,p=p,sensealg = InterpolatingAdjoint(autojacvec=ZygoteVJP()))))
end
#ERROR: MethodError: no method matching lu!(::SparseArrays.SparseMatrixCSC{Float64, Int64}, ::RowMaximum; check=false)


ForwardDiff.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(),saveat=Δt,p=p,sensealg = InterpolatingAdjoint(autojacvec=ZygoteVJP()))))
end
#1-element Vector{Float64}: -239.05656258367046
```

**Comment by raphaelchinchilla** [comment]
Addendum: I get the same error if I use ReverseDiff.jl

**Comment by ChrisRackauckas** [comment]
The original error is gone here (likely due to fixing that other issue)

```julia
using DifferentialEquations, SciMLSensitivity, Zygote, ForwardDiff, LinearAlgebra
x0 = [1.0, 0, 0, 0, 0]
tspan = (0.0, 10.0)
p = [9.8]
Δt = 0.1

## Pendulum in DAE form already simplified to index 1
function f(u, p, t)
    x, dx, y, dy, T = u
    g, = p
    [dx
        T * x
        dy
        T * y - g
        2 * (dx^2 + dy^2 + y * (y * T - g) + T * x^2)]
end

f_fun = ODEFunction{false}(f, mass_matrix=Diagonal([1, 1, 1, 1, 0]))
prob_DAE = ODEProblem{false}(f_fun, x0, tspan, p)

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(), saveat=Δt, p=p, abstol=1e-12, reltol=1e-12)))
end
#([-247.59889899360337],)

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, FBDF(), saveat=Δt, p=p, sensealg=QuadratureAdjoint(autojacvec=ZygoteVJP()), abstol=1e-10, reltol=1e-10)))
end
# ([-201.75953538790333],)

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(), saveat=Δt, p=p, sensealg=InterpolatingAdjoint(autojacvec=ZygoteVJP()), abstol=1e-12, reltol=1e-12)))
end
# ([-201.7773462456072],)

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(autodiff=false), saveat=Δt, p=p, sensealg=InterpolatingAdjoint(autojacvec=ZygoteVJP()), abstol=1e-12, reltol=1e-12)))
end
# ([-201.7773462456072],)

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(autodiff=false), saveat=Δt, p=p, sensealg=ForwardSensitivity(), abstol=1e-12, reltol=1e-12)))
end
# ([-201.7773462456072],)

ForwardDiff.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(), saveat=Δt, p=p, abstol=1e-12, reltol=1e-12)))
end
#1-element Vector{Float64}: -247.59889899360334

function f!(du, u, p, t)
    x, dx, y, dy, T = u
    g, = p
    du[1] = dx
    du[2] = T * x
    du[3] = dy
    du[4] = T * y - g
    du[5] = 2 * (dx^2 + dy^2 + y * (y * T - g) + T * x^2)
end

f_fun = ODEFunction{true}(f!, mass_matrix=Diagonal([1, 1, 1, 1, 0]))
prob_DAE = ODEProblem{true}(f_fun, x0, tspan, p)

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(), saveat=Δt, p=p, abstol=1e-12, reltol=1e-12)))
end
#([-247.5988989918497],)

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(), saveat=Δt, p=p, sensealg=InterpolatingAdjoint(autojacvec=EnzymeVJP()), abstol=1e-12, reltol=1e-12)))
end
# Expected Float64
# Need to setup the Enzyme caches as DualCache

Zygote.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(autodiff=false), saveat=Δt, p=p, sensealg=InterpolatingAdjoint(autojacvec=EnzymeVJP()), abstol=1e-12, reltol=1e-12)))
end
# ([-201.77734605640597],)

ForwardDiff.gradient(p) do p
    sum(Array(solve(prob_DAE, Rodas4(), saveat=Δt, p=p, abstol=1e-12, reltol=1e-12)))
end
#1-element Vector{Float64}: -247.59889899184972
```

@YingboMa this is odd. It seems like the adjoint is converging to a different value? I'm looking at the mass matrix implementation and that looks right though? Can you dig in?

**Comment by raphaelchinchilla** [comment]
Thanks @ChrisRackauckas for looking into this. 

It is very weird that we get two different values of gradient and that none of them match the one I had... 

Also. it still not working in my computer but I presume it is because there not a new release yet.

**Comment by ChrisRackauckas** [comment]
> It is very weird that we get two different values of gradient and that none of them match the one I had...

Well you were running it at a high tolerance so it just wasn't converged. The gradient is an equation solve so you have to be careful of that, and the default tolerances just weren't enough here. That's not an issue. The issue is that there seems to be two separate converged values. I think this may be linked to reinitialization or DAE index or something of the sort, since we haven't seen that in other DAE cases but pendulum is a bit of a difficult case (since it stems from a naturally index-2 case, but you are using the index reduction one)

**Comment by raphaelchinchilla** [comment]
> Well you were running it at a high tolerance so it just wasn't converged.

You are right, my mistake.

**Comment by YingboMa** [comment]
Note that differentiating wrt only differential variables works
```julia
julia> Zygote.gradient(p) do p
           sum(Array(solve(prob_DAE, Rodas4(), saveat=Δt, p=p, sensealg=InterpolatingAdjoint(), abstol=1e-12, reltol=1e-12))[1:4, :])
       end
([-27.3837202302557],)

julia> ForwardDiff.gradient(p) do p
           sum(Array(solve(prob_DAE, Rodas4(), saveat=Δt, p=p, abstol=1e-12, reltol=1e-12))[1:4, :])
       end
1-element Vector{Float64}:
 -27.383720232111305
```

**Comment by raphaelchinchilla** [comment]
Hummm, 

But could still be a context in which someone wants to take derivatives with respect to the no differentiable value, right? And it is mathematically consistent too I believe.

**Comment by YingboMa** [comment]
I know. I am not saying this is not an issue.

**Comment by raphaelchinchilla** [comment]
Sorry, it is actually a question,  I think it does make sense but I am not sure about it.

**Comment by ChrisRackauckas** [comment]
It just means that there is probably some correction that is missing, but it's not entirely clear where it could be.

I think I have an idea though. When we do the reverse pass there are callbacks which bump the lambda equation. The lambda equation though is a DAE with a mass matrix that is the adjoint of the original mass matrix. So when the "bumps" occur, there's a callback AND there must be a reinitialization to ensure that the new state is consistent. So lambda changes say 1 differential variable because that's what we have data for, but then an algebraic variable changes with it. Does that change to the algebraic variable need a correct term on it based on the size of the reinitialization?
