### ISSUE TITLE
Allow provided jacobians with DAE adjoint

### ISSUE THREAD

**Issue by taylormcd** [SciML/SciMLSensitivity.jl#714]
The adjoint solve fails when the user provides their own jacobian.  This is applicable when solving for the sensitivities of semi-explicit DAEs.  If you look at derivative_wrappers.jl, there is no implementation for custom jacobians, only implementations for ForwardDiff and FiniteDiff.

**Comment by taylormcd** [comment]
The line of the code that needs to change is here: https://github.com/SciML/SciMLSensitivity.jl/blob/b4fd1ce3c0cfa1db744f71319875cf7c8b2bd8d1/src/adjoint_common.jl#L469
I think the best solution is to add an if statement like the the one in the steady state adjoint: https://github.com/SciML/SciMLSensitivity.jl/blob/b4fd1ce3c0cfa1db744f71319875cf7c8b2bd8d1/src/steadystate_adjoint.jl#L91-L107
I can probably put together a basic pull request with this.

**Comment by taylormcd** [comment]
Here's a MWE based on the semi-explicit version of the pendulum problem:

```
using OrdinaryDiffEq, LinearAlgebra, SciMLSensitivity, Zygote

function f!(du, u, p, t)
    x, y, vx, vy, T = u
    g, L = p
    du[1] = vx
    du[2] = x*T
    du[3] = vy
    du[4] = y*T - g
    du[5] = 2*(vx^2 + vy^2 + y*(y*T - g) + T*x^2)
    return nothing
end

function jac!(J, u, p, t)
    x, y, vx, vy, T = u
    g, L = p
    J .= 0
    J[1,3] = 1
    J[2,1] = T
    J[2,5] = x
    J[3,4] = 1
    J[4,2] = T
    J[4,5] = y
    J[5,1] = 4*T*x
    J[5,2] = 2*(2*y*T - g)
    J[5,3] = 4*vx
    J[5,4] = 4*vy
    J[5,5] = 2*(y^2 + x^2)
    return nothing
end

func = ODEFunction(f!, mass_matrix=collect(Diagonal([1,1,1,1,0])), jac=jac!)
u0 = [1.0, 0, 0, 0, 0]; p = [9.8, 1]; tspan = (0, 10.0)
prob = ODEProblem(func, u0, tspan, p)
solve(prob,Rodas5())

function sum_of_solution(p)
    _prob = remake(prob,p=p)
    sum(solve(_prob,Rodas5(autodiff=false),saveat=0.1,sensealg=QuadratureAdjoint()))
end

dp = Zygote.gradient(sum_of_solution,p)
```

**Comment by ChrisRackauckas** [comment]
The Jacobian isn't needed to compute the adjoint though, so it's only used in fallbacks. You'd want to use the `vjp` instead.

**Comment by taylormcd** [comment]
The code and what you're saying don't seem to agree: See https://github.com/SciML/SciMLSensitivity.jl/blob/b4fd1ce3c0cfa1db744f71319875cf7c8b2bd8d1/src/adjoint_common.jl#L464-L477

**Comment by taylormcd** [comment]
Perhaps the jacobian is only needed for discrete adjoints, but not continuous adjoints?

**Comment by ChrisRackauckas** [comment]
Oh it's needed whenever the mass matrix is singular. Yeah forgot about that case.
