### ISSUE TITLE
Custom `rrule` not working

### ISSUE THREAD

**Issue by Antomek** [SciML/SciMLSensitivity.jl#735]
Hello,

I am trying to use some custom differentiation rules in differentiating a loss function of an ODE solution.

The [example from the docs](https://sensitivity.sciml.ai/stable/ad_examples/differentiating_ode/#Reverse-Mode-Automatic-Differentiation) works perfectly.
As a test, I tried to implement a custom `rrule` by adapting this example to:

```julia
using DifferentialEquations, ChainRules, ChainRulesCore

function new_gradient(x)
    println("My gradient.")
    return conj((abs(x / 2) + 1)^(-2))
end

function H(a)
    return (sign(a) + 1) / 2
end

function ϕ(x)
   return H(x) 
end

@scalar_rule ϕ(x) new_gradient(x)

using Zygote, SciMLSensitivity

function sum_of_solution(u0,p)
    _prob = remake(prob,u0=u0,p=p)
    sum(solve(_prob,Tsit5(),reltol=1e-6,abstol=1e-6,saveat=0.1))
end
du01,dp1 = Zygote.gradient(sum_of_solution,u0,p)
```

The new `rrule` isn't used, instead the actual derivative of the step function H seems to be used.
I've verified that this `rrule` does work otherwise (for example in combination with Flux).

Did I make a mistake or is `SciMLSensitivity` not compatible with `ChainRules`?

**Comment by ChrisRackauckas** [comment]
How was the problem defined? You didn't set a sensealg so if that sensealg is not using an autojacvec of ZygoteVJP then the chain rule will not be used, since ForwardDiff, Enzyme, and ReverseDiff do not use ChainRules

**Comment by Antomek** [comment]
Thanks, indeed doing

```julia
using Zygote, SciMLSensitivity

function sum_of_solution(u0,p)
    _prob = remake(prob,u0=u0,p=p)
    sum(solve(_prob,Tsit5(),reltol=1e-6,abstol=1e-6,saveat=0.1, sensealg = BacksolveAdjoint(autojacvec = ZygoteVJP())))
end
du01,dp1 = Zygote.gradient(sum_of_solution,u0,p)
```

simply works, silly mistake of me.

However, doing the same thing fails in MTK.
But as that's a ModelingToolkit question, I'll open an issue there!

**Comment by ChrisRackauckas** [comment]
MTK generates code that is fully scalarized and mutating. You do not want to use ZygoteVJP with MTK codes: it's very well-suited for Enzyme.

**Comment by Antomek** [comment]
Ah thanks!

Unfortunately, I opened [an issue](https://github.com/SciML/ModelingToolkit.jl/issues/1837) already before I spotted your comment.

Enzyme is not listed in the [list of packages supported by ChainRules](https://juliadiff.org/ChainRulesCore.jl/stable/).

Is there an easy way to get custom gradients working in MTK / Enzyme then?

**Comment by ChrisRackauckas** [comment]
At this time there isn't a great way to do it. We should make symbolic vjp functions but haven't gotten to it.
