### ISSUE TITLE
QuadratureAdjoint docstring contains nonexistent "compile" kwarg

### ISSUE THREAD

**Issue by white-alistair** [SciML/SciMLSensitivity.jl#752]
> ERROR: MethodError: no method matching QuadratureAdjoint(; autojacvec=ZygoteVJP(false), abstol=1.0e-6, reltol=1.0e-6, compile=true)
Closest candidates are:
  QuadratureAdjoint(; chunk_size, autodiff, diff_type, autojacvec, abstol, reltol) at ~/.julia/packages/SciMLSensitivity/IP3Yo/src/sensitivity_algorithms.jl:464 got unsupported keyword argument "compile"

https://github.com/SciML/SciMLSensitivity.jl/blob/6b23999c640f2f08966c9545c1e383aaba9d154c/src/sensitivity_algorithms.jl#L377-L454

**Comment by ChrisRackauckas** [comment]
Thanks! fixed.
