### ISSUE TITLE
`SECRET_DOCUMENTER_KEY` should be in repository secrets

### ISSUE THREAD

**Issue by prbzrg** [SciML/SciMLSensitivity.jl#776]
Shouldn't this be in repository secrets?
https://github.com/SciML/SciMLSensitivity.jl/blob/bcac3f11bd66e47566006bdfd6049d44cf030647/.buildkite/pipeline.yml#L78

https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by ChrisRackauckas** [comment]
No, that's the public key.
