### ISSUE TITLE
Make heavy packages into extensions?

### ISSUE THREAD

**Issue by vpuri3** [SciML/SciMLSensitivity.jl#807]
Would it make sense to turn upstream packages like Zygote, Enzyme, ReverseDiff, Tracker, and downstream packages like OrdinaryDiffEq, LinearSolve, NonlinearSolve, into extensions? Compile time for SciMLSensitivity is pretty bad

**Comment by ChrisRackauckas** [comment]
Not in SciMLSensitivity, because it uses them directly in the auto-choice algorithm.
