### ISSUE TITLE
vjp default choice

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/SciMLSensitivity.jl#813]
https://docs.sciml.ai/SciMLSensitivity/stable/manual/differential_equation_sensitivities/#SciMLSensitivity.QuadratureAdjoint
Docs give a total set of choices, with true being the default, which then uses ForwardDiff.
I thought ForwardDiff could only do jacobian free jvp, but not vjp, so I'm confused by true equating to ForwardDiff.
The constructor example also defaults to nothing, which is not a choice. If true is the default, why not put true there?

**Comment by ChrisRackauckas** [comment]
It does the vjp via jvp.

**Comment by ChrisRackauckas** [comment]
Fixed the other parts
