### ISSUE TITLE
Precompilation broken on nightly because of Cassette

### ISSUE THREAD

**Issue by anandijain** [SciML/SciMLSensitivity.jl#826]
https://github.com/JuliaLabs/Cassette.jl/issues/204

Any ideas for fixing? It seems like Cassette is only used with ReverseDiff https://github.com/SciML/SciMLSensitivity.jl/blob/ead6d82f0c1520750e5008f193f40b529c17079c/src/concrete_solve.jl#L32-L41

makes me think SciMLSensitivity might be helped with Extension packages since from a glance it seems like every AD package is loaded and maybe i don't need ReverseDiff

**Comment by ChrisRackauckas** [comment]
The only one that can be cut with extensions would be Tracker.jl, since this is mainline and part of the default.

**Comment by avik-pal** [comment]
With `1.10-alpha` SciMLSensitivity is failing to precompile due to Cassette :disappointed:. Any chance we can get it patched before the proper 1.10 release?

**Comment by sob727** [comment]
Also seeing this in 1.10.0-alpha1 and nightly (1.11.0-dev)

**Comment by avik-pal** [comment]
With https://github.com/JuliaLabs/Cassette.jl/pull/205 precompilation is fixed :tada:

**Comment by oxinabox** [comment]
This can be closed
