### ISSUE TITLE
Compute context outside of dudt function with working gradients

### ISSUE THREAD

**Issue by glatteis** [SciML/SciMLSensitivity.jl#835]
Hi! I have an encoder that gives context to a Neural SDE and I want to run it before I do my SDE solve. It's expensive to evaluate (it's an RNN that runs backwards through time), so I don't want to re-evaluate it in my dudt function. Here's an MWE: 
```
using Lux, DifferentialEquations, Random, Zygote, FiniteDiff, ComponentArrays, SciMLSensitivity

rng = Xoshiro()

context_net = Lux.Dense(1, 1)
dudt_net = Lux.Dense(1, 1)

ps_context, st_context = Lux.setup(rng, context_net)
ps_dudt, st_dudt = Lux.setup(rng, dudt_net)

p = ComponentArray((context_net=ps_context, dudt_net=ps_dudt))

tspan = (0f0, 1f0)

function loss(p)
    # context is computed outside of dudt
    context = context_net([1f0], p.context_net, st_context)[1]
  
    dudt(u, p, t) = dudt_net(context, p.dudt_net, st_dudt)[1]

    solution = solve(ODEProblem(dudt, [0f0], (0f0, 1f0), p))
    only(solution.u[end])
end

println(loss(p))
println(FiniteDiff.finite_difference_gradient(loss, p))
println(Zygote.gradient(loss, p)[1])	
```

gives (for instance)
```
1.1789757
(context_net = (weight = Float32[-1.5862626;;], bias = Float32[-1.5862626;;]), dudt_net = (weight = Float32[-0.74321616;;], bias = Float32[1.0000219;;]))
(context_net = (weight = Float32[0.0;;], bias = Float32[0.0;;]), dudt_net = (weight = Float32[-0.74323314;;], bias = Float32[1.0;;]))
```

Note the zero gradients in `context_net` with Zygote. I understand this is not how this library is "meant to be used" - to compute the VJP, your stuff should depend on the `p` that is passed through the solver. But it is still very slow to evaluate my context each time again inside the dudt. So is there some kind of solution for this? :)

**Comment by ChrisRackauckas** [comment]
`dudt(u, p, t) = dudt_net(context, p.dudt_net, st_dudt)[1]` I find this a bit confusing. This is a trivial ODE since it's `u' = constant`, so the solution is `constant * t`. What's the reason for using an ODE solver then instead of just writing down the solution?

In any case if this is an over-simplification, what you'd want to do is make `context` the parameter of the ODE so that it differentiates with respect to it instead of treating it as a constant to the ODE definition. So in other words:

```julia
    dudt(u, context, t) = dudt_net(context, p.dudt_net, st_dudt)[1]
    solution = solve(ODEProblem(dudt, [0f0], (0f0, 1f0), context))
```

**Comment by glatteis** [comment]
Thanks for your answer! Sorry for the confusion, the MWE is an oversimplification. I will try passing the context as parameter!
