### ISSUE TITLE
Latent Neural SDE implementation 100x slower than on PyTorch

### ISSUE THREAD

**Issue by glatteis** [SciML/SciMLSensitivity.jl#844]
Hi all, during my master's thesis I’m implementing Latent SDEs in Julia, but now checking back with the PyTorch implementation torchsde, that seems to be about 100x faster. They can do 200 timesteps with large batch sizes in seconds, while I can barely manage 30 timesteps with small batch sizes. It would be extremely helpful if you could help me solve this issue!

For instance, here's a three-dimensional SDE, batch size 64, 20 timesteps:

```
@time Zygote.gradient(ps -> loss(ps, select_ts(1:64, timeseries), 1.0, 1)[1], ps)[1]
=>  23.176312 seconds (43.47 M allocations: 83.214 GiB, 60.19% gc time, 1.41% compilation time)
```
It's already compiled (this is not the first run)

This is my allocation flame graph:
![image](https://github.com/SciML/SciMLSensitivity.jl/assets/8374054/738df024-086b-47a1-9d08-67bbfdd3d75d)
the big two things in the middle are my drift and diffusion, mostly evaluation of the Lux networks. The time flame graph is similar.

Code details:
- I'm using an EnsembleProblem with EnsembleThreads
- Using BacksolveAdjoint with Zygote (but InterpolatingAdjoint is even slower)
- Using Lux.jl
- Using Virtual Brownian Trees, but default noise is slower

This is where my drift/diffusion are implemented:
https://github.com/glatteis/NeuralSDEExploration/blob/747869d3603c8ddde3f0476a2a4c23cef28b8c55/src/latent.jl#L208C1-L209C1

The entire LatentSDE(…) function is run through zygote while training.

Given the performance difference there has to be some huge issue, probably something super obvious, but not to me :D

Please let me know if you need anything else or I should try something. It would be a huge relief if this would work.

**Comment by frankschae** [comment]
Is the code type stable? 
```julia
augmented_z0 = vcat(z0, zeros32(1, length(z0[1, :])))
function augmented_drift(u_in::Vector{Float64}, info::ComponentVector, t::Float64)
```
Did you try converting everything to Float32?

Probably not the biggest thing but I'd put an `@view` on array indexing calls
```julia
timedctx = context[:, Int(batch), time_index]
```

Can you measure the time it takes to compute the vector-Jacobian product of the drift and diffusion functions and compare it to your Pytorch version? 

So for the Julia version, it would be along the lines of:
```julia
y = ...
p = ...
lambda = rand(...)
_dy, back = Zygote.pullback(y, p) do u, p
                 augmented_drift(u, p, t)
            end
tmp1, tmp2 = @time back(λ)
```

@avik-pal do you see some obvious performance bugs related to using Lux here?

**Comment by avik-pal** [comment]
There seem to be quite a few Float64s used like in https://github.com/glatteis/NeuralSDEExploration/blob/9abc9f666740adc1a73f1f25bda1e88989aa863e/src/latent.jl#L123. That will drastically affect performance

**Comment by avik-pal** [comment]
Also it seems the experiments are CPU exclusive with smallish models. Lux would come close (but not be able match) Pytorch speeds there.

Maybe worth rewriting using SimpleChains.jl (not sure if it works with SciMLSensitivity) to get the best performance.

**Comment by glatteis** [comment]
```
augmented_z0 = vcat(z0, zeros32(1, length(z0[1, :])))
```
Thanks for the catch - this should be `zeros`.

@avik-pal I'm using Float64 everywhere, on CPU it should be fine right? I tried converting to Float32, but no big speed difference.

I tried to move the drift and diffusion functions out of the main body, it's a bit better but makes almost no difference:
```
@time Zygote.gradient(ps -> loss(ps, select_ts(1:64, timeseries), 1.0, 1)[1], ps)[1]
 25.220739 seconds (13.28 M allocations: 30.539 GiB, 68.28% gc time, 1.52% compilation time)
```

Maybe I should stress how huge the performance hit is. The PyTorch implementation is only using a couple of gigabytes for much larger models - 30GB should be completely unreasonable right?

**Comment by frankschae** [comment]
It seems like this is indeed a bit slow... 

Assuming that you do this once for each time step (EulerHeun) for each sample in the batch: 64 * 20 *  0.003 \approx 3.8.. (and you have to do something similar for the diffusion function.)

**Comment by glatteis** [comment]
> It seems like this is indeed a bit slow...
> 
> Assuming that you do this once for each time step (EulerHeun) for each sample in the batch: 64 * 20 * 0.003 \approx 3.8.. (and you have to do something similar for the diffusion function.)

Yeah… and the allocations are confusing. The diffusion should be cheaper.

**Comment by glatteis** [comment]
Closing this, the ensemble methods are _really_ slow, putting everything into a big solve improves everything a lot. I'm also trying to get this to work on the GPU but having some more issues (which I opened :))

**Comment by ChrisRackauckas** [comment]
Did you set `safetycopy=false` in EnsembleProblem?

**Comment by glatteis** [comment]
> Did you set `safetycopy=false` in EnsembleProblem?

no, but this is about the CPU (googling it just shows up in GPU examples)

**Comment by devmotion** [comment]
AFAIK `safetycopy` is not related to CPU/GPU: https://docs.sciml.ai/DiffEqDocs/stable/features/ensemble/#Building-a-Problem

**Comment by ChrisRackauckas** [comment]
Oh no this looks like a Zygote issue. We just need to be able to nest Enzyme instead

**Comment by glatteis** [comment]
> AFAIK `safetycopy` is not related to CPU/GPU: https://docs.sciml.ai/DiffEqDocs/stable/features/ensemble/#Building-a-Problem

You're right. I don't think I can find the time to reproduce right now though

**Comment by glatteis** [comment]
> Oh no this looks like a Zygote issue. We just need to be able to nest Enzyme instead

Yeah that would be amazing, but it seems like Enzyme isn't mature enough - I'm just getting some errors that are probably related to the level of support of Julia

**Comment by ChrisRackauckas** [comment]
It should get there in the next few months. It now has dynamic dispatch and GC support, and BLAS support just needs to be turned on. It's literally just about adding rules from NNLib now, which could be done by someone who has the time in about a week.
