### ISSUE TITLE
sol[var] etc observations do not work on ODEForwardSensitivityProblem

### ISSUE THREAD

**Issue by oxinabox** [SciML/SciMLSensitivity.jl#888]
`SciMLBase.getobserved(prob)` where `prob` was constructed via `ODEForwardSensitivityProblem`
always returns `DEFAULT_OBSERVED` -- which errors if anyone tries to read anything from it.
Even if the original problem did have observations.

My hack around this is:
```julia
function Base.getproperty(f::ODEForwardSensitivityFunction, name::Symbol)
    name == :observed && return f.f.observed
    return getfield(f, name)
end
Base.hasproperty(f::ODEForwardSensitivityFunction, name::Symbol) = (name == :observed) || hasfield(f, name)
SciMLBase.has_observed(f::ODEForwardSensitivityFunction) = SciMLBase.has_observed(f.f)
```

but possibly we should instead be passing it onwards when we make the `ODEProblem` that `ODEForwardSensitivityProblem`,
rather than relying on `getproperty` overloads.

I *think* this is correct as the equations and variables in the expanded system of equations are all placed *after* the original ones. Right?

(This is a special case of #886, but i wanted to open a seperate issue because the discussion might be nontrivial)

**Comment by ChrisRackauckas** [comment]
Yes this is correct. The unfortunate thing is that on ODEForwardSensitivityProblem, unlike the adjoints, we don't have a nice way to show their computed derivatives, even though they can be in theory calculated from the results we already have in the forward sensitivity problem.

**Comment by oxinabox** [comment]
Is the way I have as a work around valid as a PR?
 Or should I copy `observed` into the outer function?
