### ISSUE TITLE
ReverseDiffAdjoint not working with losses that call `sol.u`

### ISSUE THREAD

**Issue by nathanaelbosch** [SciML/SciMLSensitivity.jl#894]
I'm trying out the various sensitivity algorithms from this package, and ran into unexpected behaviour with `ReverseDiffAdjoint`.
When running this simple example:
```julia
using OrdinaryDiffEq, SciMLSensitivity, Zygote

function lotka_volterra(u, p, t)
    du1 = p[1]*u[1] - p[2]*u[1]*u[2]
    du2 = -p[3]*u[2] + p[4]*u[1]*u[2]
    return [du1, du2]
end
u0 = [1.0,1.0]
tspan = (0.0,10.0)
p = [1.5,1.0,3.0,1.0]
prob = ODEProblem(lotka_volterra,u0,tspan,p)

loss(u0; kwargs...) = solve(remake(prob, u0=u0), Tsit5(); kwargs...).u |> last |> sum

# works:
Zygote.gradient(loss, u0)
Zygote.gradient(u0 -> loss(u0; sensealg=TrackerAdjoint()), u0)

# does not work:
Zygote.gradient(u0 -> loss(u0; sensealg=ReverseDiffAdjoint()), u0)
```
I get this error message:
```
ERROR: type Array has no field u
```

This can be easily fixed by just casting the solution into an Array, i.e.:
```julia
loss(u0; kwargs...) = Array(solve(remake(prob, u0=u0), Tsit5(); kwargs...))[:, end] |> sum
```
but the behaviour is still quite unexpected and prevents users from witing generic readable code.

Maybe fixing this could be helpful.

**Comment by ChrisRackauckas** [comment]
I think this is somewhat fundamental to ReverseDiff.jl. It handles this transformation automatically on its end because the solution is an AbstractArray, which is an odd behavior I haven't been able to turn off.

**Comment by ThummeTo** [comment]
An *ugly* fix for this is to check for the returned solution type and pack it into an ODE solution (in the ReverseDiff case):

Pseudocode if you know your solution time points `saveat` and `prob::ODEProblem`:
```julia
import SciMLSensitivity.SciMLBase: build_solution

solution = solve(prob, args...; saveat=saveat, kwargs...) 

# ReverseDiff returns an array instead of an ODESolution, this needs to be corrected
if isa(solution, TrackedArray)
            t = collect(saveat)
            u = solution
            solution = build_solution(prob, solver, t, collect(u[:,i] for i in 1:size(u)[2]))
end
```
