### ISSUE TITLE
Only `Zygote` and `Diffractor` work?

### ISSUE THREAD

**Issue by prbzrg** [SciML/SciMLSensitivity.jl#899]
Why are we limited to only `Zygote` and `Diffractor`?

https://github.com/SciML/SciMLSensitivity.jl/blob/730cfcb9755e5fb9d4cf31d8093c80b27e155579/docs/src/manual/differential_equation_sensitivities.md?plain=1#L11-L15

**Comment by avik-pal** [comment]
The other ones don't natively support ChainRules so they wont call the correct `rrule`/`frule`.

**Comment by ChrisRackauckas** [comment]
ReverseDiff should be added to this list though.

And we should add an Enzyme rule.

**Comment by ChrisRackauckas** [comment]
This is only for drivers which end up calling into the Concrete Solve infrastructure, so no it's not the only ones that work. It's the only ones that are auto-captured.

**Comment by ChrisRackauckas** [comment]
The Enzyme rule is here: https://github.com/SciML/DiffEqBase.jl/pull/927

**Comment by ChrisRackauckas** [comment]
Closing as any specific package is either addressed or in a PR.
