### ISSUE TITLE
EnzymeVJP will not work with implicit solvers that use ForwardDiff

### ISSUE THREAD

**Issue by xzackli** [SciML/SciMLSensitivity.jl#920]
EnzymeVJP generates a fast calculation of $\lambda^{\star}(t)f_{u}(t,u(t,p),p)$ in the adjoint equation,

```math
\frac{d\lambda^{\star}}{dt}=g_{u}(u(t,p),p)-\lambda^{\star}(t)f_{u}(t,u(t,p),p),\thinspace\thinspace\thinspace\lambda^{\star}(T)=0.
```
Defining $\hat{f} \equiv \frac{d\lambda^{\star}}{dt}$, an implicit solver will want to calculate during Newton iteration $\partial \hat{f} / \partial \lambda$, the Jacobian with respect to the state. Many OrdinaryDiffEq solvers will use ForwardDiff to compute this, but will silently fail by providing a zero Jacobian to the solver. I wouldn't expect an operator-overloading AD to be able to differentiate through Enzyme-generated code.

<details>
<summary>Demo: ForwardDiff cannot AD through an Enzyme-generated function</summary>

```julia
using Enzyme, ForwardDiff

rosenbrock_inp(x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2

function g(x)
    dx = zeros(eltype(x), 2)
    autodiff_deferred(Reverse, rosenbrock_inp, Active, Duplicated(x, dx))
    return dx
end

ForwardDiff.jacobian(g, [1.0, 2.0])
```
```
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```
In practice, in SciMLSensitivity any Dual passed through the Enzyme-generated VJP will have zeros in the partials.
</details>

Fortunately, there is an easy answer. The Jacobian with respect to the state $\lambda^*$ of the adjoint equation's $\hat{f}$ is just $f_u$,
```math
\begin{aligned}
\frac{\partial \hat{f}_i}{\partial \lambda_k^*} &=  \frac{\partial}{\partial \lambda_i^*} (g_{u}(u(t,p),p)-\lambda^{\star}(t)f_{u}(t,u(t,p),p) ) = (f_u)_{ki}.
\end{aligned}
```
I'm following the SciML notation that the $u$ subscript is the gradient, but I'm using $i$, $j$, $k$ as matrix indices above. If I have this right, then we should be able to just pass the Enzyme-generated primal VJP to the adjoint ODEFunction's `vjp` argument.

**Comment by ChrisRackauckas** [comment]
@wsmoses can this case be captured and automatically error or lower to Enzyme forward mode over reverse?

**Comment by wsmoses** [comment]
I mean presumably that's just defining an frule for enzyme autodiff

**Comment by ChrisRackauckas** [comment]
For now, can Enzyme do a quick patch to error in this case? I find it surprising because I would think dual numbers would work like any other number: Julia dispatches  define a version of a function `rosenbrock_inp` and then Enzyme is applied on that function with the dual number dispatches? Seems like Enzyme is code gening based on the wrong dispatches. But this is enough of a bug that I'd hope to see an error.

**Comment by wsmoses** [comment]
I'm not actually sure Enzyme is doing anything wrong here, as it works with forward diff for other applications. I actually think here it might be some user error, or perhaps a fwddiff bug.

```
using Enzyme, ForwardDiff

rosenbrock_inp(x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2

function g(x)
    dx = zeros(eltype(x), 2)
    autodiff_deferred(Reverse, rosenbrock_inp, Active, Duplicated(x, dx))
    return dx
end

ForwardDiff.jacobian(g, [1.0, 2.0])
```

so presumably fwddiff.jl is calling g with Dual(0, 1).

that means Enzyme is called with
```
   dx = zeros(Duals, 2)
    autodiff_deferred(Reverse, rosenbrock_inp, Active, Duplicated([Dual(0, 1)...], dx))
```

a return of active will pass one(returntype) as the thing to propagate backwards. one(DualType) as defined by fwddiff i presume is (1, 0). Thus the Enzyme reverse mode here is only considering the contribution of the derivative with respect to the primal, not with respect to the fwddiff derivative (to therefore compute the second derivative).

What if you did
```
    autodiff_deferred(Reverse, x->rosenbrock_inp(x).dual, Active, Duplicated([Dual(0, 1)...], dx))
    ```

**Comment by ChrisRackauckas** [comment]
Our case isn't returning values but is mutating an array of duals

**Comment by ChrisRackauckas** [comment]
Interestingly, this pullback looks fine:

```julia
using Enzyme, ForwardDiff

function rosenbrock_inp(y,x) 
    y[1] = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
end

function g(x)
    dx = zeros(eltype(x), 2)
    y = zeros(eltype(x),1)
    dy = zero(y)
    dy[1] = 1
    autodiff_deferred(Reverse, rosenbrock_inp, Active, Duplicated(y, dy), Duplicated(x, dx))
    return y
end

ForwardDiff.jacobian(g, [1.0, 2.0])
```

**Comment by ChrisRackauckas** [comment]
ahh, it's another case of https://github.com/SciML/SciMLSensitivity.jl/issues/707. `Enzyme.Duplicated(y, tmp1)` is an odd limitation that doesn't quite make mathematical sense. We can workaround it in this case though.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLSensitivity.jl/pull/922 works around the issue

**Comment by xzackli** [comment]
That PR is wonderful, and I learned a lot from the discussion here. Thank you so much, and I'm excited to use this code to do some astrophysics!
