### ISSUE TITLE
Tagbot broken?

### ISSUE THREAD

**Issue by staticfloat** [SciML/SciMLSensitivity.jl#974]
I see the github releases seem to be out of date with the actual registrations of this package.

**Comment by ChrisRackauckas** [comment]
Yes, tagbot is broken and we noted it to people that tagbot seems to have a bug but were told to make an MWE. But since we have no idea why it is doing this or how it works, there's nothing that can be done.

**Comment by staticfloat** [comment]
Looking at the github actions logs, it looks to me like there might be an SSH key issue:

https://github.com/SciML/SciMLSensitivity.jl/actions/runs/7497764234/job/20411839262#step:3:43

**Comment by ChrisRackauckas** [comment]
Tagbot usually doesn't use a key? I usually just slap it into a repo without setting anything up and it works.

**Comment by ChrisRackauckas** [comment]
@thazhemadam can you investigate this one?

**Comment by thazhemadam** [comment]
The keys have been updated and TagBot is now running as expected.
https://github.com/SciML/SciMLSensitivity.jl/pull/980 also brings the TagBot workflow up-to-date, following the current recommended TagBot workflow setup instructions[^1].

[^1]: https://github.com/thazhemadam/TagBot/blob/16a1824512433d6aa510b6f43a9f00877510c6b9/README.md#setup
