### ISSUE TITLE
Failure to deploy docs

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/SciMLSensitivity.jl#990]
This PR fixed the making of the documentation:
https://github.com/SciML/SciMLSensitivity.jl/pull/987
But deployment still failed after it got merged in:
https://buildkite.com/julialang/scimlsensitivity-dot-jl/builds/2540#018d37f6-7d99-4f89-a959-249f8d2ae731/993-13191
I don't have the permissions to properly set up the secrets.

**Comment by ChrisRackauckas** [comment]
@thazhemadam can you look into this?

**Comment by thazhemadam** [comment]
That's odd. I'll rotate the keys again.

**Comment by ChrisRackauckas** [comment]
I just started the v7.54. Let me know if that one builds the docs.

**Comment by ArnoStrouwen** [comment]
It is still not here:
https://github.com/SciML/SciMLSensitivity.jl/tree/gh-pages
even though:
https://buildkite.com/julialang/scimlsensitivity-dot-jl/builds/2556#018d6af1-5be2-4d65-88c9-5bf8a1af5329/1078-13285

**Comment by ArnoStrouwen** [comment]
Ok, it is finally working:
https://docs.sciml.ai/SciMLSensitivity/stable/
